apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: app-tls
  namespace: doc-custom
spec:
  secretName: app-tls
  issuerRef:
    name: letsencrypt-nginx
    kind: ClusterIssuer
  dnsNames:
    - ai.doc-custom.oondemand.com.br
