apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-doc-custom
  namespace: doc-custom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-doc-custom
  template:
    metadata:
      labels:
        app: ai-doc-custom
    spec:
      containers:
        - name: ai-doc-custom-container
          image: ghcr.io/oondemand/api-integracao-gpt:${IMAGE_TAG}
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "${NODE_ENV}"
            - name: OPEN_IA_SECRET_KEY
              value: "${OPEN_IA_SECRET_KEY}"
            - name: JWT_SECRET
              value: "${JWT_SECRET}"
          resources:
            requests:
              memory: "256Mi"
              cpu: "0.1"
            limits:
              memory: "2048Mi"
              cpu: "2"
