apiVersion: v1
kind: Service
metadata:
  name: ai-doc-custom-service
  namespace: doc-custom
spec:
  type: NodePort
  selector:
    app: ai-doc-custom
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
